Retrigger builds on restart
wtsi-hgi/go-softpack-builder pull request #21
Opened 2024-02-22 13:59 UTC by sersorrel

now we shouldn't lose progress on builds when g-s-b is restarted!

Depends on https://github.com/wtsi-hgi/softpack-core/pull/48.

2024-02-22 14:04 UTC, mjkw31 submitted a review, later dismissed
LGTM.

2024-02-22 16:36 UTC, sb10 requested changes
Some missed docs

2024-02-22 16:36 UTC, sb10 commented on core/core.go
> +type ResendResponse struct {
Public methods here and below need documenting.

2024-02-22 16:36 UTC, sb10 commented on internal/wrmock/mock.go
> +func NewMockWR(pollForStatusInterval, jobDuration time.Duration) *MockWR {
Needs public docs

2024-02-22 16:36 UTC, sb10 commented on remove/remove.go
> +	slog.Info(fmt.Sprintf("Removing env %s from core\n", envPath))
lowercase first letter in logs messages

2024-02-22 16:36 UTC, sb10 commented on server/server.go
> +	waitUntilStartedTimeout = 10 * time.Second
Increase this timeout, since apparently the re-send can seem quite slow?

2024-02-22 16:36 UTC, sb10 commented on server/server.go
> +// service talk to us. Will only work if we were configured with core details
talks

2024-02-23 10:06 UTC, sb10 approved these changes

2024-02-23 10:10 UTC, merged